[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://api-gateway.umami.dev"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"